version: '3.8'

services:
  tronpy_api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/tronpy_api


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: